import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link
					href="https://api.mapbox.com/mapbox-gl-js/v2.5.1/mapbox-gl.css"
					rel="stylesheet"
				/>

				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1>Hello</h1>
				<Link href="/elpers">To Posts</Link>
			</main>
		</div>
	);
}
